
<br /><br />
<div id="page-wrapper" >
   
        <div class="col-lg-9">   

            <form role="form" id="novo" method="post"  action="<?php print URL;?>grupo/novo" class="form form-horizontal" >
                <hr>
                <div class="form-group">
                    <label>Nome do Grupo</label>
                    <input type="text" class="form-control"  placeholder="Insira" name="nome" />
                </div>
                <input type="hidden"  name="guardar" value="1"/>
                <div class="form-group">
                    <label for="">Descricao</label>
                    <input type="text" class="form-control"  placeholder="Insira" name="descricao" />
                </div>

                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-saved"></i>Guardar Dados</button>
            </form>

        </div>
    </div>




