




<div class="row-fluid">
    <!-- block -->
    <div class="block">

        <div id="pageContent"></div>
        <div id="esconder">
            <div class="navbar navbar-inner block-header">
                <div class="muted text-center text-info"><h3>Para mais informações selecciona o usuario</h3></div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <div class="table-toolbar">
                        <div class="btn-group">
                            <a href="<?php print URL . $this->link; ?>"><button class="btn btn-success">Novo Usuario <i class="icon-plus icon-white"></i></button></a>
                        </div>

                    </div>

                    <table  class="table table-striped table-bordered">   
                        <thead>
                            <tr>
                                <th>Nome</th> 
                                <th>Alterar</th> 
                                <th>Apagar</th> 
                                <th>Retirar da Rede</th> 

                            </tr>
                        </thead>

                        <tbody>
                            <?php if (isset($this->usuario) && !empty($this->usuario)): ?>

                                <?php foreach ($this->usuario as $value):
                                    ?>
                                    <tr>
                                        <td><a href="<?php print URL . "usuario/dados/" . $value ?>" ><?php print $value; ?></a></td>
                                        <td><a rel="<?php echo $value; ?>" href="#" id="altera"><i class="glyphicon glyphicon-pencil">Alterar</i></a></td>
                                        <td><a rel="<?php echo $value; ?>" href="#" id="delete"><i class="glyphicon glyphicon-trash">Apagar</i></a></td>
                                        <td><a rel="<?php echo $value; ?>" href="#" id="retira"><i class="glyphicon glyphicon-trash">retirar</i></a></td>

                                    </tr>
                                <?php endforeach; ?> 
                            </tbody>
                        </table>
                    <?php else: ?>
                        <h2 class="text-center text-error">Nenhum usuario cadastrado</h2>
                    <?php endif; ?>

                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <hr>