<br /><br /><br /><br />

<h3 class="text-center"><?php if (isset($this->titulo)) print $this->titulo; ?></h3>
<div class="container">

    <div id="open">
        <!-------->
        <div id="esconder"> 
            <div id="content">
                <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                    <li class="active"><a href="#data" data-toggle="tab">Data</a></li>
                    <li><a href="#senha" data-toggle="tab">Senha</a></li>
                </ul>
                <div id="my-tab-content" class="tab-content">
                    <div class="tab-pane active" id="data">
                        <hr>
                        <div class="col-xs-6 col-sm-4">
                            <form role="form" id="novo" method="post"  action="<?php print URL; ?>usuario/editardata" class="form form-horizontal" >
                                <input type="hidden"  name="guardar" value="1">
                                <input type="hidden"  name="usuario" value="<?php echo $this->usuario; ?>">
                                <div class="form-group">
                                    <label class="control-label">Data<span class="required">*</span></label>
                                    <input type="text" data-field="datetime" readonly name="data" class="span6 m-wrap">
                                    <div id="dtBox"></div>
                                </div>

                                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-saved pull-left"></i>Atualizar Dados</button>
                            </form>
                        </div>
                    </div> <!--- fim alterar data!--->

                    <div class="tab-pane" id="senha">

                        <hr>
                        <div class="col-xs-6 col-sm-4">
                            <form role="form" id="novo" method="post"  action="<?php print URL; ?>usuario/editarsenha" class="form form-horizontal" >
                                <input type="hidden"  name="guardar" value="1">
                                <input type="hidden"  name="usuario" value="<?php echo $this->usuario; ?>">
                                <div class="control-group">
                                    <label class="control-label">Senha<span class="required">*</span></label>
                                    <div class="controls">
                                        <input name="senha" type="text" class="span6 m-wrap"/>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-saved pull-left"></i>Atualizar Dados</button>
                            </form>
                        </div>

                    </div> <!--- fim alterar senha!--->
                </div>
            </div>
        </div> <!-- container -->
    </div>
