
<div class="row-fluid" id="cliente">
    <!-- block -->
    <div class="block">
        <div class="navbar navbar-inner block-header">
            <div class="muted pull-left"><?php print $this->titulo; ?></div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">
                <div class="table-toolbar">
                    <div class="btn-group">
                        <a href="<?php print URL; ?>usuario"><button class="btn btn-success" id="">Voltar<i class="icon-fast-backward icon-white"></i></button></a>
                    </div>
                </div>

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>

                            <th>Nome</th> 
                            <th>Login</th>
                            <th>Data de Expiração</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->usuario) && !empty($this->usuario)): ?>

                            <tr>
                                <td>
                                    <?php print $this->usuario->displayName; ?></td>
                                <td><?php print $this->usuario->samaccountname; ?></td>
                                <td><?php print convert_AD_date($this->usuario->accountexpires); ?></td>
                            </tr>
                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center alert-error">Nenhuma Informação a ser  mostrada</h2>
                <?php endif; ?>

            </div>
        </div>
    </div>
    <!-- /block -->
</div>
</div>
</div>
<hr>
